---
Name: masqueradeconfig
---
SilverStripe\Security\Member:
  extensions:
    - DHensby\Masquerade\Extensions\MasqueradeMemberExtension
SilverStripe\Admin\SecurityAdmin:
  extensions:
    - DHensby\Masquerade\Extensions\MasqueradeSecurityAdminExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    masquerade/css/masquerade.css:
      media: screen
