---
Name: masqueradeconfig
---
SilverStripe\Security\Member:
  extensions:
    - MasqueradeMemberExtension
SilverStripe\Security\SecurityAdmin:
  extensions:
    - MasqueradeSecurityAdminExtension
LeftAndMain:
  extra_requirements_css:
    masquerade/css/masquerade.css:
      media: screen
